openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  # Added by API Auto Mocking Plugin
  
  # Added by API Auto Mocking Plugin
 
  # Added by API Auto Mocking Plugin
  
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/ISHAAABDUL23/EmployeeAPI/1.0.0
  - description: SwaggerHub API Auto Mocking
    url: "http://localhost:5283/"
info:
  version: "1.0.0"
  title: Employee API
  description: Endpoints of CRUD of employee.

paths:
  /api/Employee:
    get:
      tags:
        - Employee
      summary: Returns all employee.
      responses:
        '200':
         description: Success
         content:
           application/json:
            schema:
              $ref: '#/components/schemas/Employee'
    post:
      tags:
        - Employee
      summary: Adds new employee
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee' 
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
        
  /api/Employee/{id}:
    get:
      tags:
        - Employee
      summary: Returns employee of given id
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        '200':
         description: Success
         content:
           application/json:
           
            schema:
              $ref: '#/components/schemas/Employee'
    put:
      tags:
        - Employee
      summary: Updates employee details
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        '200':
         description: Success
         content:
           application/json:
            
            schema:
              $ref: '#/components/schemas/Employee'
    delete:
      tags:
        - Employee      
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'  
    
      
  
components:
  schemas: 
    Employee:
      
      properties:
        id:
          type: integer
        name:
          type: string
        age: 
          type: integer
