openapi: 3.0.0
info:
  description: Endpoints of CRUD of employee.
  title: Employee API
  version: 1.0.0
servers:
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/ISHAAABDUL23/EmployeeAPI/1.0.0
- description: SwaggerHub API Auto Mocking
  url: http://localhost:5283/
paths:
  /api/Employee:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
          description: Success
      summary: Returns all employee.
      tags:
      - Employee
      x-accepts: application/json
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Employee'
                type: array
          description: Success
      summary: Adds new employee
      tags:
      - Employee
      x-content-type: application/json
      x-accepts: application/json
  /api/Employee/{id}:
    delete:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Employee'
                type: array
          description: Success
      tags:
      - Employee
      x-accepts: application/json
    get:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
          description: Success
      summary: Returns employee of given id
      tags:
      - Employee
      x-accepts: application/json
    put:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
          description: Success
      summary: Updates employee details
      tags:
      - Employee
      x-accepts: application/json
components:
  schemas:
    Employee:
      example:
        name: name
        id: 0
        age: 6
      properties:
        id:
          type: integer
        name:
          type: string
        age:
          type: integer

