name: Delete and Recreate Folder

on:
  push:
    branches:
      - main

jobs:
  delete_and_recreate_folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Delete Existing Folder
        run: rm -rf ${{ github.workspace }}/gosdk

      - name: Create New Folder
        run: mkdir ${{ github.workspace }}/new-sdk

      # Additional steps can be added here, such as generating content, copying files, etc.

      - name: Commit and Push Changes
        run: |
          git config --local user.email "ishaaidayatullah19@siesgst.ac.in"
          git config --local user.name "Ishaa-23"

          # Check if there are changes in the repository
          if [ -n "$(git status --porcelain)" ]; then
            git add --all
            git commit -m "Delete and recreate folder"
            git push origin main
          else
            echo "No changes to commit."
          fi
