name: Generate and Add SDK

on:
  push:
    branches:
      - main

jobs:
  generate_and_add_sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install OpenAPI Generator
        run: npm install -g @openapitools/openapi-generator-cli@latest
      
      - name: Configure Git for C# SDK
        run: |
          git config --global user.email "ishaaidayatullah19@siesgst.ac.in"
          git config --global user.name "Ishaa-23"

      - name: Delete Existing SDK
        run: rm -rf ${{ github.workspace }}/gosdk/*
      - name: Committing
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add --all
            git commit -m "Delete folder content"
            git push origin main
          else
            echo "No changes to commit."
          fi
      
    
      - name: Generate SDK
        run: |
          openapi-generator-cli generate --verbose -i combined.yaml -g go -o ${{ github.workspace }}/gosdk --package-name Combinedapi
      - name: Committing
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add --all
            git commit -m "Committing sdk to folder"
            git push origin main
          else
            echo "No changes to commit."
          fi
      - name: Set variable
        run: | 
             echo "repo_name=Go-Package" >> $GITHUB_ENV
             echo "user_name=Ishaa-23"   >> $GITHUB_ENV
        
      - name: Delete go.mod
        run: |
          rm -f ${{ github.workspace }}/gosdk/go.mod
          cd gosdk
          go mod init github.com/${user_name}/$(repo_name)
             
      - name: Committing
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add --all
            git commit -m "Renaming github generic"
            git push origin main
          else
            echo "No changes to commit."
          fi
      - name: Push gosdk to Go-Package
        run: |
          
          cd gosdk
          git init
          git add .
          git commit -m "Push gosdk folder from Automate repository"
          git branch -M main
          
          git push --force https://${{ secrets.sdk }}@github.com/$(user_name)/$(repo_name).git main
      

     
