name: Generate and Add SDK

on:
  push:
    branches:
      - main
env:
  GIT_USER_EMAIL: "ishaaidayatullah19@siesgst.ac.in"
  REPO_OWNER: "Ishaa-23"
  REPO_NAME: "Go-package"
  TOKEN: ${{ secrets.sdk }}
jobs:
  generate_and_add_sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install OpenAPI Generator
        run: npm install -g @openapitools/openapi-generator-cli@latest
      
      - name: Configure Git for C# SDK
        run: |
          git config --global user.email "ishaaidayatullah19@siesgst.ac.in"
          git config --global user.name "Ishaa-23"

      - name: Delete Existing SDK
        run: rm -rf ${{ github.workspace }}/gosdk/*
      - name: Committing
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add --all
            git commit -m "Delete folder content"
            git push origin main
          else
            echo "No changes to commit."
          fi
      
    
      - name: Generate SDK
        run: |
          openapi-generator-cli generate --verbose -i combined.yaml -g go -o ${{ github.workspace }}/gosdk --package-name Combinedapi
      - name: Committing
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add --all
            git commit -m "Committing sdk to folder"
            git push origin main
          else
            echo "No changes to commit."
          fi
     
        
      - name: Delete go.mod
        run: |
          rm -f ${{ github.workspace }}/gosdk/go.mod
          cd gosdk
          go mod init github.com/${REPO_OWNER}/${REPO_NAME}
             
      - name: Committing
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add --all
            git commit -m "Renaming github generic"
            git push origin main
          else
            echo "No changes to commit."
          fi
      
      - name: Configure Git for C# SDK
        run: |
          git config --global user.email "ishaaidayatullah19@siesgst.ac.in"
          git config --global user.name "Ishaa-23"
      - name: Delete Contents of Go-Package
        run: |
          
          # Get the latest commit SHA
          LATEST_COMMIT_SHA=$(git rev-parse HEAD)

          # Get the list of files in the repository
          FILES=$(curl -s -H "Authorization: token $TOKEN" \
                    "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/git/trees/$LATEST_COMMIT_SHA?recursive=1" | \
                    jq -r '.tree[] | .path')

          # Delete each file in the repository
          for FILE in $FILES; do
            curl -X DELETE -H "Authorization: token $TOKEN" \
              "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/contents/$FILE" \
              -d "{\"message\": \"Delete $FILE\", \"sha\": \"$LATEST_COMMIT_SHA\"}"
          done
      - name: Push gosdk to Go-Package
        run: |
          cd gosdk
          git init
          git add .
          git commit -m "Push gosdk folder from Automate repository"
          git branch -M main
          
          git push --force https://${{ secrets.sdk }}@github.com/${REPO_OWNER}/${REPO_NAME}.git main
      

     
