name: Generate and Add SDK

on:
  push:
    branches:
      - main
env:
  GIT_USER_EMAIL: "ishaaidayatullah19@siesgst.ac.in"
  REPO_OWNER: "Ishaa-23"
  REPO_NAME: "Go-package"
  TOKEN: ${{ secrets.sdk }}
jobs:
  generate_and_add_sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install OpenAPI Generator
        run: npm install -g @openapitools/openapi-generator-cli@latest
      
      - name: Configure Git for C# SDK
        run: |
          git config --global user.email "ishaaidayatullah19@siesgst.ac.in"
          git config --global user.name "Ishaa-23"

      - name: Delete Existing SDK
        run: |
             rm -rf ${{ github.workspace }}/gosdk/*
             rm -rf ${{ github.workspace }}/javasdk/*
      - name: Committing
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add --all
            git commit -m "Delete folder content"
            git push origin main
          else
            echo "No changes to commit."
          fi
      
    
      - name: Generate SDK
        run: |
          openapi-generator-cli generate --verbose -i combined.yaml -g java -o ${{ github.workspace }}/javasdk --package-name Combinedapi
      - name: Committing
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add --all
            git commit -m "Committing sdk to folder"
            git push origin main
          else
            echo "No changes to commit."
          fi
     
      - name: Commit and Force Push SDK to go-package
        run: |
          cd javasdk
          git init
          git add .
          git commit -m "Push java-sdk folder from Automate repository"
          git branch -M main
          git remote add origin https://${{ secrets.sdk }}@github.com/Ishaa-23/Java-package.git
          git push --force origin main
