name: Generate and Add SDK

on:
  push:
    branches:
      - main

jobs:
  generate_and_add_sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install OpenAPI Generator
        run: npm install -g @openapitools/openapi-generator-cli@latest

      - name: Generate SDK
        run: |
          openapi-generator-cli generate --verbose -i combined.yaml -g go -o ${{ github.workspace }}/gosdk --package-name Combinedapi

      - name: Commit generated SDK
        run: |
          git config --local user.email "ishaaidayatullah19@siesgst.ac.in"
          git config --local user.name "Ishaa-23"

          # Check if there are changes in the repository
          if [ -n "$(git status --porcelain)" ]; then
            git add --all
            git commit -m "Add generated SDK"

            # Use GITHUB_TOKEN for authentication
            git push origin main
          else
            echo "No changes to commit."
          fi
